code --install-extension alefragnani.Bookmarks &&
code --install-extension chrmarti.regex &&
code --install-extension CoenraadS.bracket-pair-colorizer &&
code --install-extension dbaeumer.vscode-eslint &&
code --install-extension dsznajder.es7-react-js-snippets &&
code --install-extension eamodio.gitlens &&
code --install-extension esbenp.prettier-vscode &&
code --install-extension formulahendry.code-runner &&
code --install-extension hollowtree.vue-snippets &&
code --install-extension HookyQR.beautify &&
code --install-extension ionutvmi.path-autocomplete &&
code --install-extension james-yu.latex-workshop &&
code --install-extension mechatroner.rainbow-csv &&
code --install-extension ms-azuretools.vscode-docker &&
code --install-extension msjsdiag.debugger-for-chrome &&
code --install-extension octref.vetur &&
code --install-extension PKief.material-icon-theme &&
code --install-extension ritwickdey.LiveServer &&
code --install-extension shd101wyy.markdown-preview-enhanced &&
code --install-extension streetsidesoftware.code-spell-checker &&
code --install-extension taichi.vscode-textlint &&
code --install-extension yzhang.markdown-all-in-one 
