# 基本コマンドのエイリアス
alias ls='ls -G'
alias ll='ls -l'
alias la='ls -A'
alias lla='ls -lA'
alias l='ls -CF'
alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'
alias mkdir='mkdir -p'
alias df='df -h'
alias du='du -h'
alias free='free -m'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias diff='diff -u'

# Git関連のエイリアス
alias git='git'
alias ga='git add'
alias gd='git diff'
alias gs='git status'
alias gp='git push'
alias gb='git branch'
alias gst='git status'
alias gco='git checkout'
alias gf='git fetch'
alias gc='git commit'
alias gcm='git commit -m'
alias gpl='git pull'
alias gcl='git clone'
alias gl='git log'
alias glo='git log --oneline'
alias glg='git log --graph'
alias gst='git stash'
alias gstp='git stash pop'

# ディレクトリ移動のエイリアス
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'
alias ~='cd ~'
alias -- -='cd -'

# プロセスのエイリアス
alias ps='ps aux'
alias psg='ps aux | grep'

# システム関連のエイリアス
alias sudo='sudo '
alias su='su -'
alias reboot='sudo reboot'
alias shutdown='sudo shutdown -h now'
alias poweroff='sudo poweroff'

# ネットワーク関連のエイリアス
alias ip='ip -color'
alias ipconfig='ifconfig'
alias netstat='netstat -tulanp'
alias ports='netstat -tulanp'
alias listen='lsof -i'

# 開発関連のエイリアス
alias py='python'
alias py3='python3'
alias pip='pip3'
alias venv='python3 -m venv'
alias activate='source venv/bin/activate'

# Docker関連のエイリアス
alias d='docker'
alias dc='docker-compose'
alias dps='docker ps'
alias di='docker images'
alias dex='docker exec -it'

# Kubernetes関連のエイリアス
alias k='kubectl'
alias kg='kubectl get'
alias kd='kubectl describe'
alias kl='kubectl logs'
alias ka='kubectl apply -f'
alias kx='kubectl exec -it'

# その他の便利なエイリアス
alias c='clear'
alias h='history'
alias j='jobs -l'
alias path='echo -e ${PATH//:/\\n}'
alias now='date +"%T"'
alias nowtime=now
alias nowdate='date +"%d-%m-%Y"'
alias vi='vim'
alias v='vim'
alias s='source'
alias zshrc='vim ~/.zshrc'
alias reload='source ~/.zshrc'
alias cls='clear'
alias q='exit'
alias :q='exit'
alias bye='exit'
alias quit='exit'
alias x='exit' 