#!/bin/bash

export CONFIG_DIR="$HOME/.config/sketchybar"
export PLUGIN_DIR="$CONFIG_DIR/plugins"
export ITEM_DIR="$CONFIG_DIR/items"

source "$CONFIG_DIR/colors.sh"
source "$CONFIG_DIR/icons.sh"

launchctl unload -F /System/Library/LaunchAgents/com.apple.OSDUIHelper.plist > /dev/null 2>&1 &

source "$CONFIG_DIR/bar.sh"
source "$CONFIG_DIR/default.sh"

source "$ITEM_DIR/spaces.sh"
source "$ITEM_DIR/front_app.sh"

source "$ITEM_DIR/widgets.sh"

sketchybar --update

sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$(aerospace list-workspaces --focused 2>/dev/null || echo "1")

echo "sketchybar configuration loaded..."
